export const mymensinghInfo = [
  {
    division: "Mymensingh",
    districts: [
      {
        nameofdistrict: "Mymensingh",
        upazilas: [
          {
            nameOfUpazilaOrThana: "Bhaluka",
            unions: [
              { nameOfUnion: "Habirbari" },
              { nameOfUnion: "Rajoi" },
              { nameOfUnion: "Bhaluka" },
              { nameOfUnion: "Uthura" },
              { nameOfUnion: "Meduari" },
              { nameOfUnion: "Varadoba" },
              { nameOfUnion: "Dhitpur" },
              { nameOfUnion: "Dakatia" },
              { nameOfUnion: "Birunia" },
              { nameOfUnion: "Mallikbari" },
              { nameOfUnion: "Kachina" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Fullbaria",
            unions: [
              { nameOfUnion: "Deukhola" },
              { nameOfUnion: "Naogaon" },
              { nameOfUnion: "Putijana" },
              { nameOfUnion: "Kushmail" },
              { nameOfUnion: "Fulbaria" },
              { nameOfUnion: "Bakta" },
              { nameOfUnion: "Rangamatia" },
              { nameOfUnion: "Enayetpur" },
              { nameOfUnion: "Kaladaha" },
              { nameOfUnion: "Radhakanai" },
              { nameOfUnion: "Asimpatuli" },
              { nameOfUnion: "Vobanipur" },
              { nameOfUnion: "Balian" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Gaffargaon",
            unions: [
              { nameOfUnion: "Rasulpur" },
              { nameOfUnion: "Barobaria" },
              { nameOfUnion: "Charalgi" },
              { nameOfUnion: "Saltia" },
              { nameOfUnion: "Raona" },
              { nameOfUnion: "Longair" },
              { nameOfUnion: "Paithol" },
              { nameOfUnion: "Gafargaon" },
              { nameOfUnion: "Josora" },
              { nameOfUnion: "Moshakhali" },
              { nameOfUnion: "Panchbagh" },
              { nameOfUnion: "Usthi" },
              { nameOfUnion: "Dotterbazar" },
              { nameOfUnion: "Niguari" },
              { nameOfUnion: "Tangabo" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Gauripur",
            unions: [
              { nameOfUnion: "Deukhola" },
              { nameOfUnion: "Naogaon" },
              { nameOfUnion: "Putijana" },
              { nameOfUnion: "Kushmail" },
              { nameOfUnion: "Fulbaria" },
              { nameOfUnion: "Bakta" },
              { nameOfUnion: "Rangamatia" },
              { nameOfUnion: "Enayetpur" },
              { nameOfUnion: "Kaladaha" },
              { nameOfUnion: "Radhakanai" },
              { nameOfUnion: "Asimpatuli" },
              { nameOfUnion: "Vobanipur" },
              { nameOfUnion: "Balian" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Haluaghat",
            unions: [
              { nameOfUnion: "Bhubankura" },
              { nameOfUnion: "Jugli" },
              { nameOfUnion: "Kaichapur" },
              { nameOfUnion: "Haluaghat" },
              { nameOfUnion: "Gazirbhita" },
              { nameOfUnion: "Bildora" },
              { nameOfUnion: "Sakuai" },
              { nameOfUnion: "Narail" },
              { nameOfUnion: "Dhara" },
              { nameOfUnion: "Dhurail" },
              { nameOfUnion: "Amtoil" },
              { nameOfUnion: "Swadeshi" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Ishwarganj",
            unions: [
              { nameOfUnion: "Iswarganj" },
              { nameOfUnion: "Sarisha" },
              { nameOfUnion: "Sohagi" },
              { nameOfUnion: "Atharabari" },
              { nameOfUnion: "Rajibpur" },
              { nameOfUnion: "Maijbagh" },
              { nameOfUnion: "Magtula" },
              { nameOfUnion: "Jatia" },
              { nameOfUnion: "Uchakhila" },
              { nameOfUnion: "Tarundia" },
              { nameOfUnion: "Barahit" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Mymensingh Sadar",
            unions: [
              { nameOfUnion: "Austadhar" },
              { nameOfUnion: "Bororchar" },
              { nameOfUnion: "Dapunia" },
              { nameOfUnion: "Aqua" },
              { nameOfUnion: "Khagdohor" },
              { nameOfUnion: "Charnilaxmia" },
              { nameOfUnion: "Kushtia" },
              { nameOfUnion: "Paranganj" },
              { nameOfUnion: "Sirta" },
              { nameOfUnion: "Charishwardia" },
              { nameOfUnion: "Ghagra" },
              { nameOfUnion: "Vabokhali" },
              { nameOfUnion: "Boyra" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Muktagachha",
            unions: [
              { nameOfUnion: "Dulla" },
              { nameOfUnion: "Borogram" },
              { nameOfUnion: "Tarati" },
              { nameOfUnion: "Kumargata" },
              { nameOfUnion: "Basati" },
              { nameOfUnion: "Mankon" },
              { nameOfUnion: "Ghoga" },
              { nameOfUnion: "Daogaon" },
              { nameOfUnion: "Kashimpur" },
              { nameOfUnion: "Kheruajani" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Nandail",
            unions: [
              { nameOfUnion: "Batagoir" },
              { nameOfUnion: "Nandail" },
              { nameOfUnion: "Chandipasha" },
              { nameOfUnion: "Gangail" },
              { nameOfUnion: "Rajgati" },
              { nameOfUnion: "Muajjempur" },
              { nameOfUnion: "Sherpur" },
              { nameOfUnion: "Singroil" },
              { nameOfUnion: "Achargaon" },
              { nameOfUnion: "Mushulli" },
              { nameOfUnion: "Kharua" },
              { nameOfUnion: "Jahangirpur" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Phulpur",
            unions: [
              { nameOfUnion: "Deukhola" },
              { nameOfUnion: "Naogaon" },
              { nameOfUnion: "Putijana" },
              { nameOfUnion: "Kushmail" },
              { nameOfUnion: "Fulbaria" },
              { nameOfUnion: "Bakta" },
              { nameOfUnion: "Rangamatia" },
              { nameOfUnion: "Enayetpur" },
              { nameOfUnion: "Kaladaha" },
              { nameOfUnion: "Radhakanai" },
              { nameOfUnion: "Asimpatuli" },
              { nameOfUnion: "Vobanipur" },
              { nameOfUnion: "Balian" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Trishal",
            unions: [
              { nameOfUnion: "Dhanikhola" },
              { nameOfUnion: "Bailor" },
              { nameOfUnion: "Kanthal" },
              { nameOfUnion: "Kanihari" },
              { nameOfUnion: "Trishal" },
              { nameOfUnion: "Harirampur" },
              { nameOfUnion: "Balipara" },
              { nameOfUnion: "Mokshapur" },
              { nameOfUnion: "Mathbari" },
              { nameOfUnion: "Amirabari" },
              { nameOfUnion: "Rampur" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Tara Khanda",
            unions: [
              { nameOfUnion: "Balikha" },
              { nameOfUnion: "Banihala" },
              { nameOfUnion: "Biska" },
              { nameOfUnion: "Galagaon" },
              { nameOfUnion: "Kakni" },
              { nameOfUnion: " Kamargaon" },
              { nameOfUnion: "Kamaria" },
              { nameOfUnion: "Rampur" },
              { nameOfUnion: "Tarakanda" },
            ],
          },
        ],
      },
      {
        nameofdistrict: "Sherpur",
        upazilas: [
          {
            nameOfUpazilaOrThana: "Sherpur Sadar Upazila",
            unions: [
              { nameOfUnion: "Kamararchor" },
              { nameOfUnion: "Chorsherpur" },
              { nameOfUnion: "Bajitkhila" },
              { nameOfUnion: "Gajirkhamar" },
              { nameOfUnion: "Dhola" },
              { nameOfUnion: "Pakuriya" },
              { nameOfUnion: "Vatshala" },
              { nameOfUnion: "Losmonpur" },
              { nameOfUnion: "Rouha" },
              { nameOfUnion: "Kamariya" },
              { nameOfUnion: "Chormochoriya" },
              { nameOfUnion: "Chorpokhimari" },
              { nameOfUnion: "Betmarighughurakandi" },
              { nameOfUnion: "Balairchar" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Nalitabari",
            unions: [
              { nameOfUnion: "Puraga" },
              { nameOfUnion: "Nonni" },
              { nameOfUnion: "Morichpuran" },
              { nameOfUnion: "Rajnogor" },
              { nameOfUnion: "Nayabil" },
              { nameOfUnion: "Ramchondrokura" },
              { nameOfUnion: "Kakorkandhi" },
              { nameOfUnion: "Nalitabari" },
              { nameOfUnion: "Juganiya" },
              { nameOfUnion: "Bagber" },
              { nameOfUnion: "Koloshpar" },
              { nameOfUnion: "Rupnarayankura" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Sreebardi",
            unions: [
              { nameOfUnion: "Ranishimul" },
              { nameOfUnion: "Singabaruna" },
              { nameOfUnion: "Kakilakura" },
              { nameOfUnion: "Tatihati" },
              { nameOfUnion: "Gosaipur" },
              { nameOfUnion: "Sreebordi" },
              { nameOfUnion: "Bhelua" },
              { nameOfUnion: "Khariakazirchar" },
              { nameOfUnion: "Kurikahonia" },
              { nameOfUnion: "Garjaripa" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Jhenaigati",
            unions: [
              { nameOfUnion: "Kansa" },
              { nameOfUnion: "Dansail" },
              { nameOfUnion: "Nolkura" },
              { nameOfUnion: "Gouripur" },
              { nameOfUnion: "Jhenaigati" },
              { nameOfUnion: "Hatibandha" },
              { nameOfUnion: "Malijhikanda" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Nakla",
            unions: [
              { nameOfUnion: "Gonopoddi" },
              { nameOfUnion: "Nokla" },
              { nameOfUnion: "Urpha" },
              { nameOfUnion: "Gourdwar" },
              { nameOfUnion: "Baneshwardi" },
              { nameOfUnion: "Pathakata" },
              { nameOfUnion: "Talki" },
              { nameOfUnion: "Choraustadhar" },
              { nameOfUnion: "Chandrakona" },
            ],
          },
        ],
      },
      {
        nameofdistrict: "Jamalpur",
        upazilas: [
          {
            nameOfUpazilaOrThana: "Baksiganj ",
            unions: [
              { nameOfUnion: "Danua" },
              { nameOfUnion: "Bagarchar" },
              { nameOfUnion: "Battajore" },
              { nameOfUnion: "Shadurpara" },
              { nameOfUnion: "Bakshigonj" },
              { nameOfUnion: "Nilakhia" },
              { nameOfUnion: "Merurchar" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Dewanganj ",
            unions: [
              { nameOfUnion: "Dungdhara" },
              { nameOfUnion: "Charamkhawa" },
              { nameOfUnion: "Parramrampur" },
              { nameOfUnion: "Hatibanga" },
              { nameOfUnion: "Bahadurabad" },
              { nameOfUnion: "Chikajani" },
              { nameOfUnion: "Chukaibari" },
              { nameOfUnion: "Dewangonj" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Islampur ",
            unions: [
              { nameOfUnion: "Kulkandi" },
              { nameOfUnion: "Belghacha" },
              { nameOfUnion: "Chinaduli" },
              { nameOfUnion: "Shapdari" },
              { nameOfUnion: "Noarpara" },
              { nameOfUnion: "Islampur" },
              { nameOfUnion: "Partharshi" },
              { nameOfUnion: "Palabandha" },
              { nameOfUnion: "Gualerchar" },
              { nameOfUnion: "Gaibandha" },
              { nameOfUnion: "Charputimari" },
              { nameOfUnion: "Chargualini" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Jamalpur Sadar ",
            unions: [
              { nameOfUnion: "Kendua" },
              { nameOfUnion: "Sharifpur" },
              { nameOfUnion: "Laxirchar" },
              { nameOfUnion: "Tolshirchar" },
              { nameOfUnion: "Itail" },
              { nameOfUnion: "Narundi" },
              { nameOfUnion: "Ghorada" },
              { nameOfUnion: "Bashchara" },
              { nameOfUnion: "Ranagacha" },
              { nameOfUnion: "Sheepur" },
              { nameOfUnion: "Shahbajpur" },
              { nameOfUnion: "Titpalla" },
              { nameOfUnion: "Mesta" },
              { nameOfUnion: "Digpait" },
              { nameOfUnion: "Rashidpur" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Madarganj ",
            unions: [
              { nameOfUnion: "Charpakerdah" },
              { nameOfUnion: "Karaichara" },
              { nameOfUnion: "Gunaritala" },
              { nameOfUnion: "Balijuri" },
              { nameOfUnion: "Jorekhali" },
              { nameOfUnion: "Adarvita" },
              { nameOfUnion: "Sidhuli" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Melandaha ",
            unions: [
              { nameOfUnion: "Durmot" },
              { nameOfUnion: "Kulia" },
              { nameOfUnion: "Mahmudpur" },
              { nameOfUnion: "Nangla" },
              { nameOfUnion: "Nayanagar" },
              { nameOfUnion: "Adra" },
              { nameOfUnion: "Charbanipakuria" },
              { nameOfUnion: "Fulkucha" },
              { nameOfUnion: "Ghuserpara" },
              { nameOfUnion: "Jhaugara" },
              { nameOfUnion: "Shuampur" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Sarishabari ",
            unions: [
              { nameOfUnion: "Satpoa" },
              { nameOfUnion: "Pogaldigha" },
              { nameOfUnion: "Doail" },
              { nameOfUnion: "Aona" },
              { nameOfUnion: "Pingna" },
              { nameOfUnion: "Bhatara" },
              { nameOfUnion: "Kamrabad" },
              { nameOfUnion: "Mahadan" },
            ],
          },
        ],
      },

      {
        nameofdistrict: "Netrokona",
        upazilas: [
          {
            nameOfUpazilaOrThana: "Atpara ",
            unions: [
              { nameOfUnion: "Shormushia" },
              { nameOfUnion: "Shunoi" },
              { nameOfUnion: "Lunesshor" },
              { nameOfUnion: "Baniyajan" },
              { nameOfUnion: "Teligati" },
              { nameOfUnion: "Duoj" },
              { nameOfUnion: "Sukhari" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Barhatta ",
            unions: [
              { nameOfUnion: "Asma" },
              { nameOfUnion: "Chhiram" },
              { nameOfUnion: "Baushi" },
              { nameOfUnion: "Barhatta" },
              { nameOfUnion: "Raypur" },
              { nameOfUnion: "Sahata" },
              { nameOfUnion: "Singdha" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Durgapur ",
            unions: [
              { nameOfUnion: "Durgapur" },
              { nameOfUnion: "Kakoirgora" },
              { nameOfUnion: "Kullagora" },
              { nameOfUnion: "Chandigarh" },
              { nameOfUnion: "Birisiri" },
              { nameOfUnion: "Bakaljora" },
              { nameOfUnion: "Gawkandia" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Khaliajuri ",
            unions: [
              { nameOfUnion: "Krishnapur" },
              { nameOfUnion: "Nogor" },
              { nameOfUnion: "Chakua" },
              { nameOfUnion: "Khaliajuri" },
              { nameOfUnion: "Mendipur" },
              { nameOfUnion: "Gazipur" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Kalmakanda ",
            unions: [
              { nameOfUnion: "Koilati" },
              { nameOfUnion: "Najirpur" },
              { nameOfUnion: "Pogla" },
              { nameOfUnion: "Kolmakanda" },
              { nameOfUnion: "Rongchati" },
              { nameOfUnion: "Lengura" },
              { nameOfUnion: "Borokhapon" },
              { nameOfUnion: "Kharnoi" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Kendua ",
            unions: [
              { nameOfUnion: "Asujia" },
              { nameOfUnion: "Dalpa" },
              { nameOfUnion: "Goraduba" },
              { nameOfUnion: "Gonda" },
              { nameOfUnion: "Sandikona" },
              { nameOfUnion: "Maska" },
              { nameOfUnion: "Bolaishimul" },
              { nameOfUnion: "Noapara" },
              { nameOfUnion: "Kandiura" },
              { nameOfUnion: "Chirang" },
              { nameOfUnion: "Roailbariamtala" },
              { nameOfUnion: "Paikura" },
              { nameOfUnion: "Muzafarpur" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Madan ",
            unions: [
              { nameOfUnion: "Fathepur" },
              { nameOfUnion: "Nayekpur" },
              { nameOfUnion: "Teosree" },
              { nameOfUnion: "Magan" },
              { nameOfUnion: "Gobindasree" },
              { nameOfUnion: "Madan" },
              { nameOfUnion: "Chandgaw" },
              { nameOfUnion: "Kytail" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Mohanganj ",
            unions: [
              { nameOfUnion: "Borokashiabirampur" },
              { nameOfUnion: "Borotolibanihari" },
              { nameOfUnion: "Tetulia" },
              { nameOfUnion: "Maghansiadar" },
              { nameOfUnion: "Somajsohildeo" },
              { nameOfUnion: "Suair" },
              { nameOfUnion: "Gaglajur" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Netrokona Sadar ",
            unions: [
              { nameOfUnion: "Chollisha" },
              { nameOfUnion: "Kailati" },
              { nameOfUnion: "Dokkhinbishiura" },
              { nameOfUnion: "Modonpur" },
              { nameOfUnion: "Amtola" },
              { nameOfUnion: "Lokkhiganj" },
              { nameOfUnion: "Singherbangla" },
              { nameOfUnion: "Thakurakona" },
              { nameOfUnion: "Mougati" },
              { nameOfUnion: "Rouha" },
              { nameOfUnion: "Medni" },
              { nameOfUnion: "Kaliaragabragati" },
            ],
          },
          {
            nameOfUpazilaOrThana: "Purbadhala ",
            unions: [
              { nameOfUnion: "Khalishaur" },
              { nameOfUnion: "Ghagra" },
              { nameOfUnion: "Jaria" },
              { nameOfUnion: "Narandia" },
              { nameOfUnion: "Bishkakuni" },
              { nameOfUnion: "Bairaty" },
              { nameOfUnion: "Hogla" },
              { nameOfUnion: "Gohalakanda" },
              { nameOfUnion: "Dhalamulgaon" },
              { nameOfUnion: "Agia" },
              { nameOfUnion: "Purbadhala" },
            ],
          },
        ],
      },
    ],
  },
];
